[package]
name = "voiceland_internal_tests"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
# rsmpeg = { workspace = true }
voiceland_protocol = { path = "../voiceland_protocol" }
