[package]
name = "voiceland_protocol"
version = "0.1.0"
edition = "2021"
license = "AGPL-3.0"

[dependencies]
anyhow = { workspace = true }
#serde = { workspace = true }
#rsmpeg = { workspace = true }

#num-traits = "0.2"
#num-derive = "0.4"
